name: Build data.json from CSV

on:
  push:
    branches: [ main ]
    paths:
      - 'spotlight-firms-data.csv'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: write  # needed so the workflow can commit data.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install papaparse
        run: npm init -y && npm install papaparse

      - name: Generate data.json
        run: node scripts/csv_to_json.js

      - name: Commit updated data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "chore: rebuild data.json from CSV" || echo "No changes to commit"
          git push
